#FROM nvidia/cuda:12.1.1-devel-ubuntu20.04
#FROM nvidia/cuda:11.7.1-cudnn8-devel-ubuntu20.04
#FROM nvcr.io/nvidia/pytorch:22.12-py3
FROM nvcr.io/nvidia/pytorch:23.12-py3
#FROM nvcr.io/nvidia/cuda:12.3.1-devel-ubuntu22.04
#FROM nvidia/cuda:12.1.0-cudnn8-devel-ubuntu20.04

#FROM nvcr.io/nvidia/pytorch:21.10-py3
#FROM nvidia/cuda:11.4.1-cudnn8-devel-ubuntu20.04 

ENV TZ=America/New_York
RUN pip install tqdm plyfile

# ENV DEBIAN_FRONTEND=noninteractive
# RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
# 
# RUN apt update 
# #### Install cmake from Kitware ####
# RUN apt-get install -y ca-certificates gpg wget
# RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
# RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | tee /etc/apt/sources.list.d/kitware.list >/dev/null
# RUN apt-get update
# RUN rm /usr/share/keyrings/kitware-archive-keyring.gpg
# RUN apt-get install -y kitware-archive-keyring
# RUN echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal-rc main' | tee -a /etc/apt/sources.list.d/kitware.list >/dev/null
# RUN apt-get update
# RUN apt-get install -y cmake
# RUN cmake --version
# #####################################
# 
# RUN apt install -y git zstd libboost-all-dev protobuf-compiler \
#     libprotobuf-dev pkg-config libpython3-dev python3-numpy lsb-release wget \
#     libeigen3-dev pcl-tools libpcl-dev python3-opencv libopencv*-dev \
#     gstreamer1.0-plugins-ugly gstreamer1.0-plugins-bad libxrandr-dev
# #RUN apt update
# RUN apt install -y libgstreamer-plugins-*